WIP: Add register hotkey
bennetthardwick/rust-obs-plugins pull request #8
Opened 2020-11-22 13:31 UTC by bennetthardwick

2020-11-22 14:33 UTC, chengyuhui commented on src/source/context.rs
> +        Box<dyn FnMut(&mut Hotkey, &mut Option<D>)>,
Maybe we pass the hotkey ID to the callback as well? Since this is in the API anyway.

2020-11-23 09:32 UTC, bennetthardwick commented on src/source/context.rs
> +        Box<dyn FnMut(&mut Hotkey, &mut Option<D>)>,
I suppose that can be added to `Hotkey` instead of being added as another param. There's also a method called `obs_hotkey_get_id` that lets you get a hotkey from the id.

2020-11-23 09:33 UTC, bennetthardwick commented
@chengyuhui when you get a chance can you see if this works for you? I tried it with the scroll focus filter and it didn't work.

2020-11-23 09:54 UTC, chengyuhui commented
Well, maybe later today, currently working on courseworks.
I think maybe we've got something wrong as this feature is used everywhere (it's poorly documented anyway).

2020-11-23 10:46 UTC, bennetthardwick commented
Tested again, this time with a `SourceType::INPUT` instead of a `SourceType::FILTER` and it seems to work. I think obs just doesn't support showing hotkeys for filters.

2020-11-23 13:43 UTC, chengyuhui commented
Just finished troubleshooting my PC and had some time to test, LGTM.

2020-11-24 13:11 UTC, bennetthardwick commented
@chengyuhui can you take another look when you get a chance? I merged in those `DataObj` changes.

2020-11-24 13:26 UTC, chengyuhui commented
I found that we still have problems in texture mapping (crashes OBS), gonna fix that first.

2020-11-24 13:46 UTC, chengyuhui commented on src/source/context.rs
> +    }
```suggestion
    pub fn register_hotkey<F: FnMut(&mut Hotkey, &mut Option<D>) + 'static>(
        &mut self,
        name: ObsString,
        description: ObsString,
        func: F,
    ) {
        self.hotkey_callbacks
            .push((name, description, Box::new(func)));
    }
```
Requiring the user to box them looks bad.

2020-11-24 13:47 UTC, chengyuhui requested changes
Implementation tested, LGTM.

2020-11-25 11:47 UTC, merged